name: 🚀 Deploy to Appointment-app VPS

on:
  push:
    branches:
      - main  # or master if that’s your branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            sudo apt update
            sudo apt upgrade
            cd ${{ secrets.VPS_APP_PATH }}
            git pull origin main
            cd client && npm install && npm run build && mv ./dist/ /var/www/smart-visitors/ && cd ..
            pm2 restart smart-visitors || pm2 start index.js --name "smart-visitors"
            sudo systemctl reload nginx


# /var/www/smart-visitors/